
import { useState } from 'react';
import NewWindow from 'react-new-window';
 
import Head from "next/head";
import Image from "next/image";
import Layout from "../components/layout";
import styles from "../styles/Home.module.css";
import Services from "./services";
import About from "./about";
import Testimonial from "./testimonial";
import Contact from "./contact";
import { signOut, useSession } from 'next-auth/react';

export default function Home() {
  const [popup, setPopUp] = useState(false);
   const {session,loading}=useSession()
  return (
    <>
    {/* start */}
    <div>
      {loading ? (
        <p>loading session...</p>
      ) : session ? (
        <button onClick={() => signOut()}>Logout</button>
      ) : (
        <button onClick={() => setPopUp(true)}>Login</button>
      )}

      {popup && !session ? (
        <NewWindow url="/sign-in" onUnload={() => setPopUp(false)} />
      ) : null}
    </div>
    {/* end */}
      <Head>
        <title>palours</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Services />
        <About />
        <Testimonial />
        <Contact />
      </Layout>
    </>
  );
}
