import Head from "next/head";
import Image from "next/image";
import Layout from "../components/layout";
import styles from "../styles/Home.module.css";
import Services from "./services";
import About from "./about";
import Testimonial from "./testimonial";
import Contact from "./contact";
export default function Home() {
  return (
    <>
      <Head>
        <title>palours</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Services />
        <About />
        <Testimonial />
        <Contact />
      </Layout>
    </>
  );
}
