import Head from "next/head";
import Image from "next/image";
import Layout from "../components/layout";

const testimonial = () => {
  return (
    <>
      <Head>
        <title>palours</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"
          integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm"
          crossOrigin="anonymous"
        ></link>
      </Head>
      <div style={{ backgroundColor: "#fff8f5" }}>
        <div className="text-center mt-3 p-2">
          <h2 className="fw-bold">Testimonial</h2>
        </div>

        {/* <div className="carousel-inner">
        <div className="carousel-item active">
          <Image
            src="/Ellipse 90.png"
            className="d-block w-100"
            width={64}
            height={64}
            alt="review-1"
          />
        </div>
        <div className="carousel-item">
          <Image
            src="/Ellipse 91.png"
            className="d-block w-100"
            width={64}
            height={64}
            alt="review-2"
          />
        </div>
        <div className="carousel-item">
          <Image
            src="/Ellipse 92.png"
            className="d-block w-100"
            width={64}
            height={64}
            alt="review-3"
          />
        </div>
      </div> */}

        {/* custom testimonial */}
        <div className="container">
          <div className="row">
            <div className="col-lg-4 ">
              <div className="card m-2 p-3">
                <div className="face front-face">
                  <div className="d-flex align-items-center justify-content-around p-2 m-1  ">
                    <Image
                      src="/Ellipse 90.png"
                      className="d-block w-100  "
                      width={64}
                      height={64}
                      alt="review-1"
                    />

                    <div>
                      <h4 className="fw-bold">Robert Garrison</h4>
                      <p>Robert Garrison</p>
                    </div>
                  </div>
                </div>
                <div>
                  <p
                    className="card-text text-center  m-1 p-2  fs-5"
                    style={{ color: "#646464" }}
                  >
                    This is a wider card with supporting text below as a natural
                    lead-in to additional content. This content is a little bit
                    longer.
                  </p>
                </div>
                <div className="text-center p-2 m-2">
                  <i className="far fa-star"></i>
                  <i className="far fa-star"></i>
                  <i className="far fa-star"></i>
                  <i className="far fa-star"></i>
                </div>
              </div>
            </div>
            <div className="col-lg-4 ">
              <div className="card m-2 p-3">
                <div className="face front-face">
                  <div className="d-flex align-items-center justify-content-around p-2 m-1  ">
                    <Image
                      src="/Ellipse 91.png"
                      className="d-block w-100  "
                      width={64}
                      height={64}
                      alt="review-1"
                    />

                    <div>
                      <h4 className="fw-bold">Robert Garrison</h4>
                      <p>Robert Garrison</p>
                    </div>
                  </div>
                </div>
                <div>
                  <p
                    className="card-text text-center  m-1 p-2  fs-5"
                    style={{ color: "#646464" }}
                  >
                    This is a wider card with supporting text below as a natural
                    lead-in to additional content. This content is a little bit
                    longer.
                  </p>
                </div>
                <div className="text-center p-2 m-2">
                  <i className="far fa-star"></i>
                  <i className="far fa-star"></i>
                  <i className="far fa-star"></i>
                  <i className="far fa-star"></i>
                </div>
              </div>
            </div>
            <div className="col-lg-4 ">
              <div className="card m-2 p-3">
                <div className="face front-face">
                  <div className="d-flex align-items-center justify-content-around p-2 m-1  ">
                    <Image
                      src="/Ellipse 92.png"
                      className="d-block w-100  "
                      width={64}
                      height={64}
                      alt="review-1"
                    />

                    <div>
                      <h4 className="fw-bold">Robert Garrison</h4>
                      <p>Robert Garrison</p>
                    </div>
                  </div>
                </div>
                <div>
                  <p
                    className="card-text text-center  m-1 p-2  fs-5"
                    style={{ color: "#646464" }}
                  >
                    This is a wider card with supporting text below as a natural
                    lead-in to additional content. This content is a little bit
                    longer.
                  </p>
                </div>
                <div className="text-center p-2 m-2">
                  <i className="far fa-star"></i>
                  <i className="far fa-star"></i>
                  <i className="far fa-star"></i>
                  <i className="far fa-star"></i>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default testimonial;
